name: memories
description: Memories Photo App

dependency_overrides:
  flutter:
    sdk: flutter
  location: ^1.4.1
  http: ^0.11.3
  # camera: ^0.2.3
  camera: ^0.5.2+2
  # video_player: ^0.6.5
  video_player: ^0.10.1+5
  # video_player: ^0.10.1+3
  path_provider: ^0.4.1
  # flutter_svg: ^0.5.5
  flutter_svg: ^0.13.1
  simple_permissions: ^0.1.9  
  image_picker_saver: ^0.1.0
  image_picker: ^0.4.10
  font_awesome_flutter: "^8.0.1"
  rxdart: "^0.18.0"
  mime: ^0.9.6
  chewie: ^0.8.0
  dio: ^2.1.0
  percent_indicator: ^1.0.14
  photo_view: ^0.3.1
  carousel_slider: ^1.3.0
  # geolocator: ^5.0.1




  # image_downloader: ^0.9.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
